spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/schoolregistration
    username: schoolregistration
    password: schoolregistration
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

application:
  maximumStudentsPerCourse: 50
  maximumCoursesPerStudent: 5
