spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolregistration
    username: schoolregistration
    password: schoolregistration
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
